apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: host.docker.internal:5432
    database: traffic_lake
    user: traffic_user
    secureJsonData:
      password: "Youngkorea970919"
    jsonData:
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
      postgresVersion: 15
      timescaledb: false

